var eStory1 = 
[{"LineNum":1.0,"word":"Sam went into his room to work on some homework assignments for school.","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":1.0}},
{"LineNum":2.0,"word":"He thought about the report he had to write for his Shakespeare class.","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":1.0}},
{"LineNum":3.0,"word":"He considered all of his options and decided to write an essay about Macbeth.","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":1.0}},
{"LineNum":4.0,"word":"He opened his backpack and took his class notebook out of his bag.","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":1.0}},
{"LineNum":5.0,"word":"Sam shuffled through some papers and began to organize his notes from class.","data":{"testphase":"encoding","Condition":"Pre-control","ConditionNum":3.0,"CB":1.0,"StoryNum":1.0}},
{"LineNum":6.0,"word":"A moment later, Sam felt relieved to have organized notes to start from.","data":{"testphase":"encoding","Condition":"Control","ConditionNum":4.0,"CB":1.0,"StoryNum":1.0}},
{"LineNum":7.0,"word":"He thought about the plot and started brainstorming thesis ideas for the report.","data":{"testphase":"encoding","Condition":"Pre-boundary","ConditionNum":1.0,"CB":1.0,"StoryNum":1.0}},
{"LineNum":8.0,"word":"A while later, Sam thought about two other classes for which he had read the play. ","data":{"testphase":"encoding","Condition":"Boundary","ConditionNum":2.0,"CB":1.0,"StoryNum":1.0}},
{"LineNum":9.0,"word":"He took out a blank piece of paper and started outlining his report.","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":1.0}},
{"LineNum":10.0,"word":"Sam heard the phone ring but did not answer it.","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":1.0}},
{"LineNum":11.0,"word":"His sister told him it was for her since she was looking for a job.","data":{"testphase":"encoding","Condition":"Pre-boundary","ConditionNum":1.0,"CB":1.0,"StoryNum":1.0}},
{"LineNum":12.0,"word":"A while later, he thought about her college graduation ceremony last month.","data":{"testphase":"encoding","Condition":"Boundary","ConditionNum":2.0,"CB":1.0,"StoryNum":1.0}},
{"LineNum":13.0,"word":"Sam jotted down some notes about how to write his introduction.","data":{"testphase":"encoding","Condition":"Pre-control","ConditionNum":3.0,"CB":1.0,"StoryNum":1.0}},
{"LineNum":14.0,"word":"A moment later, with a good outline it was time to start typing the report.","data":{"testphase":"encoding","Condition":"Control","ConditionNum":4.0,"CB":1.0,"StoryNum":1.0}},
{"LineNum":15.0,"word":"He turned on his computer and switched on his monitor.","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":1.0}},
{"LineNum":16.0,"word":"Sam was starting to get hungry and considered taking a break.","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":1.0}},
{"LineNum":17.0,"word":"He thought about ordering a pizza from his favorite Italian place.","data":{"testphase":"encoding","Condition":"Pre-boundary","ConditionNum":1.0,"CB":1.0,"StoryNum":1.0}},
{"LineNum":18.0,"word":"A while later, he briefly looked around his room for snacks but tried not to get distracted","data":{"testphase":"encoding","Condition":"Boundary","ConditionNum":2.0,"CB":1.0,"StoryNum":1.0}},
{"LineNum":19.0,"word":"He decided to continue working to try to make more progress.","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":1.0}},
{"LineNum":20.0,"word":"He looked over his outline again and realized he needed some additional information.","data":{"testphase":"encoding","Condition":"Pre-control","ConditionNum":3.0,"CB":1.0,"StoryNum":1.0}},
{"LineNum":21.0,"word":"A moment later, he took out a volume of Shakespeare's Collected Works for reference.","data":{"testphase":"encoding","Condition":"Control","ConditionNum":4.0,"CB":1.0,"StoryNum":1.0}},
{"LineNum":22.0,"word":"He started to feel his eyes getting tired from looking at the monitor.","data":{"testphase":"encoding","Condition":"Pre-control","ConditionNum":3.0,"CB":1.0,"StoryNum":1.0}},
{"LineNum":23.0,"word":"A moment later, Sam put on his glasses so he could see the screen clearly.","data":{"testphase":"encoding","Condition":"Control","ConditionNum":4.0,"CB":1.0,"StoryNum":1.0}},
{"LineNum":24.0,"word":"He remembered they were old and wrote himself a note to get a new prescription.","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":1.0}},
{"LineNum":25.0,"word":"He turned on some music to help him focus on his work.","data":{"testphase":"encoding","Condition":"Pre-boundary","ConditionNum":1.0,"CB":1.0,"StoryNum":1.0}},
{"LineNum":26.0,"word":"A while later, he discovered some very useful information and made a few notes.","data":{"testphase":"encoding","Condition":"Boundary","ConditionNum":2.0,"CB":1.0,"StoryNum":1.0}},
{"LineNum":27.0,"word":"He checked over the requirements for the assignment one more time.","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":1.0}},
{"LineNum":28.0,"word":"Sam looked over his notes for the introduction and made some revisions.","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":1.0}},
{"LineNum":29.0,"word":"He thought about how his teacher emphasized the importance of the introduction.","data":{"testphase":"encoding","Condition":"Pre-control","ConditionNum":3.0,"CB":1.0,"StoryNum":1.0}},
{"LineNum":30.0,"word":"A moment later, he tried to come up with interesting ways to draw the reader into the paper.","data":{"testphase":"encoding","Condition":"Control","ConditionNum":4.0,"CB":1.0,"StoryNum":1.0}},
{"LineNum":31.0,"word":"He settled on a theme and started to type out his introduction.","data":{"testphase":"encoding","Condition":"Pre-boundary","ConditionNum":1.0,"CB":1.0,"StoryNum":1.0}},
{"LineNum":32.0,"word":"A while later, Sam started to realize that he enjoyed the teacher's challenging assignments.","data":{"testphase":"encoding","Condition":"Boundary","ConditionNum":2.0,"CB":1.0,"StoryNum":1.0}},
{"LineNum":33.0,"word":"Sam typed up a few supporting lines and started working on his final paragraph.","data":{"testphase":"encoding","Condition":"Pre-control","ConditionNum":3.0,"CB":1.0,"StoryNum":1.0}},
{"LineNum":34.0,"word":"A moment later, he looked at a bag of chips that was sitting on his desk.","data":{"testphase":"encoding","Condition":"Control","ConditionNum":4.0,"CB":1.0,"StoryNum":1.0}},
{"LineNum":35.0,"word":"He tasted one and found out they were too stale to eat.","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":1.0}},
{"LineNum":36.0,"word":"He heard his sister in the bathroom getting ready for bed.","data":{"testphase":"encoding","Condition":"Pre-boundary","ConditionNum":1.0,"CB":1.0,"StoryNum":1.0}},
{"LineNum":37.0,"word":"A while later, Sam finished typing up the last paragraph of his report.","data":{"testphase":"encoding","Condition":"Boundary","ConditionNum":2.0,"CB":1.0,"StoryNum":1.0}},
{"LineNum":38.0,"word":"He took a last look over it, printed it out, and went to bed.","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":1.0}}]
