var eStory2 = 
[{"LineNum":1,"word":"Nancy arrived at her apartment after a long day of work. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1,"StoryNum":2}},
{"LineNum":2,"word":"She tidied up her bedroom since it was a bit of a mess. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1,"StoryNum":2}},
{"LineNum":3,"word":"She noticed that she had left her stereo on all day.","data":{"testphase":"encoding","Condition":"Pre-control","ConditionNum":3.0,"CB":1,"StoryNum":2}},
{"LineNum":4,"word":"A moment later, Nancy's stomach started to growl loudly since she had not eaten lunch. ","data":{"testphase":"encoding","Condition":"Control","ConditionNum":4.0,"CB":1,"StoryNum":2}},
{"LineNum":5,"word":"She decided to finish up some things from the office before preparing dinner. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1,"StoryNum":2}},
{"LineNum":6,"word":"Nancy was still thinking about food even while she did her work.  ","data":{"testphase":"encoding","Condition":"Pre-boundary","ConditionNum":1.0,"CB":1,"StoryNum":2}},
{"LineNum":7,"word":"A while later, she tried to decide what kind of meal to prepare. ","data":{"testphase":"encoding","Condition":"Boundary","ConditionNum":2.0,"CB":1,"StoryNum":2}},
{"LineNum":8,"word":"She took out some things from the pantry and refrigerator.","data":{"testphase":"encoding","Condition":"Pre-control","ConditionNum":3.0,"CB":1,"StoryNum":2}},
{"LineNum":9,"word":"A moment later, she turned on her stove to heat up a pot of water. ","data":{"testphase":"encoding","Condition":"Control","ConditionNum":4.0,"CB":1,"StoryNum":2}},
{"LineNum":10,"word":"Nancy noticed that her apartment was warm that evening. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1,"StoryNum":2}},
{"LineNum":11,"word":"She realized she had forgotten to leave a window open when she left for work.","data":{"testphase":"encoding","Condition":"Pre-control","ConditionNum":3.0,"CB":1,"StoryNum":2}},
{"LineNum":12,"word":"A moment later, she decided to turn on the air conditioner for a little while. ","data":{"testphase":"encoding","Condition":"Control","ConditionNum":4.0,"CB":1,"StoryNum":2}},
{"LineNum":13,"word":"Nancy got herself a drink because she was thirsty. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1,"StoryNum":2}},
{"LineNum":14,"word":"She put a few spices into tomato sauce and heated it up in a saucepan.","data":{"testphase":"encoding","Condition":"Pre-boundary","ConditionNum":1.0,"CB":1,"StoryNum":2}},
{"LineNum":15,"word":"A while later, Nancy put some pasta in the pot and added some salt to the water. ","data":{"testphase":"encoding","Condition":"Boundary","ConditionNum":2.0,"CB":1,"StoryNum":2}},
{"LineNum":16,"word":"She set the kitchen table with a placemat, a glass and silverware. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1,"StoryNum":2}},
{"LineNum":17,"word":"Nancy thought about turning on the television since she had not watched it lately. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1,"StoryNum":2}},
{"LineNum":18,"word":"She decided she would rather read the newspaper while her dinner cooked. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1,"StoryNum":2}},
{"LineNum":19,"word":"She picked it up and opened it to the Op-Ed section.","data":{"testphase":"encoding","Condition":"Pre-control","ConditionNum":3.0,"CB":1,"StoryNum":2}},
{"LineNum":20,"word":"A moment later, she checked her dinner and prepared a plate when it was ready. ","data":{"testphase":"encoding","Condition":"Control","ConditionNum":4.0,"CB":1,"StoryNum":2}},
{"LineNum":21,"word":"She grabbed a napkin to wipe up some sauce that had spilled. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1,"StoryNum":2}},
{"LineNum":22,"word":"She turned on the television because she wanted to watch the Simpsons. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1,"StoryNum":2}},
{"LineNum":23,"word":"Nancy remembered that there were movies at the theater that she wanted to see. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1,"StoryNum":2}},
{"LineNum":24,"word":"She finished eating and called one of her friends about seeing a movie.","data":{"testphase":"encoding","Condition":"Pre-boundary","ConditionNum":1.0,"CB":1,"StoryNum":2}},
{"LineNum":25,"word":"A while later, she decided to clean up her dirty dishes before doing anything else. ","data":{"testphase":"encoding","Condition":"Boundary","ConditionNum":2.0,"CB":1,"StoryNum":2}},
{"LineNum":26,"word":"She filled the sink with water to first soak the dishes.","data":{"testphase":"encoding","Condition":"Pre-control","ConditionNum":3.0,"CB":1,"StoryNum":2}},
{"LineNum":27,"word":"A moment later, she added some dish soap to the water and watched the sink fill with bubbles. ","data":{"testphase":"encoding","Condition":"Control","ConditionNum":4.0,"CB":1,"StoryNum":2}},
{"LineNum":28,"word":"Nancy put the soap on a sponge and got started.","data":{"testphase":"encoding","Condition":"Pre-boundary","ConditionNum":1.0,"CB":1,"StoryNum":2}},
{"LineNum":29,"word":"A while later, she turned on the radio to listen to some music. ","data":{"testphase":"encoding","Condition":"Boundary","ConditionNum":2.0,"CB":1,"StoryNum":2}},
{"LineNum":30,"word":"She sang along to one of her favorite songs from high school. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1,"StoryNum":2}},
{"LineNum":31,"word":"Her voice got hoarse from all the singing she was doing.","data":{"testphase":"encoding","Condition":"Pre-control","ConditionNum":3.0,"CB":1,"StoryNum":2}},
{"LineNum":32,"word":"A moment later, she left the dishes in the rack on the counter to dry. ","data":{"testphase":"encoding","Condition":"Control","ConditionNum":4.0,"CB":1,"StoryNum":2}},
{"LineNum":33,"word":"She decided to read for a little bit before going to bed.","data":{"testphase":"encoding","Condition":"Pre-boundary","ConditionNum":1.0,"CB":1,"StoryNum":2}},
{"LineNum":34,"word":"A while later, she remembered that she drank a cup of coffee before leaving work. ","data":{"testphase":"encoding","Condition":"Boundary","ConditionNum":2.0,"CB":1,"StoryNum":2}},
{"LineNum":35,"word":"She took out a book that she thought would make her feel tired. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1,"StoryNum":2}},
{"LineNum":36,"word":"Nancy read her book and hoped she would be able to sleep.","data":{"testphase":"encoding","Condition":"Pre-boundary","ConditionNum":1.0,"CB":1,"StoryNum":2}},
{"LineNum":37,"word":"A while later, her cat came into the room and brushed her foot with his tail. ","data":{"testphase":"encoding","Condition":"Boundary","ConditionNum":2.0,"CB":1,"StoryNum":2}},
{"LineNum":38,"word":"She finished a few chapters, then turned off the lights and fell asleep.","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1,"StoryNum":2}}];
