var eStory3 = 
[{"LineNum":1.0,"word":"Angie was on her way to the local laundromat on Saturday morning.","data": {"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":3.0}},
{"LineNum":2.0,"word":"As she arrived she saw somebody from her yoga class and said hello.","data": {"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":3.0}},
{"LineNum":3.0,"word":"She went into the laundromat and looked around for an open washer.","data": {"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":3.0}},
{"LineNum":4.0,"word":"An employee came up to her and apologized because they were very busy.","data": {"testphase":"encoding","Condition":"Pre-control","ConditionNum":3.0,"CB":1.0,"StoryNum":3.0}},
{"LineNum":5.0,"word":"A moment later, some washers started to open up while she waited.","data": {"testphase":"encoding","Condition":"Control","ConditionNum":4.0,"CB":1.0,"StoryNum":3.0}},
{"LineNum":6.0,"word":"When it was her turn she put her bags on top of an open machine.","data": {"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":3.0}},
{"LineNum":7.0,"word":"She threw away an empty soda can that was on the floor.","data": {"testphase":"encoding","Condition":"Pre-control","ConditionNum":3.0,"CB":1.0,"StoryNum":3.0}},
{"LineNum":8.0,"word":"A moment later, she put four coins into the washing machine to get it started.","data": {"testphase":"encoding","Condition":"Control","ConditionNum":4.0,"CB":1.0,"StoryNum":3.0}},
{"LineNum":9.0,"word":"Angie measured out a cup of detergent and added it to the water.","data": {"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":3.0}},
{"LineNum":10.0,"word":"She remembered two shirts she had ruined when the colors ran.","data": {"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":3.0}},
{"LineNum":11.0,"word":"She separated light and dark clothes and finished preparing the machine.","data": {"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":3.0}},
{"LineNum":12.0,"word":"She watched as the dark clothes spun in the machine.","data": {"testphase":"encoding","Condition":"Pre-boundary","ConditionNum":1.0,"CB":1.0,"StoryNum":3.0}},
{"LineNum":13.0,"word":"A while later, she smiled at a child who was playing with a ball nearby.","data": {"testphase":"encoding","Condition":"Boundary","ConditionNum":2.0,"CB":1.0,"StoryNum":3.0}},
{"LineNum":14.0,"word":"She started another washing machine for her light colored clothes.","data": {"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":3.0}},
{"LineNum":15.0,"word":"She poured in some bleach for the stains on her white clothes.","data": {"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":3.0}},
{"LineNum":16.0,"word":"She added a pair of slacks she had forgotten as the machine ran.","data": {"testphase":"encoding","Condition":"Pre-control","ConditionNum":3.0,"CB":1.0,"StoryNum":3.0}},
{"LineNum":17.0,"word":"A moment later, she walked over to a vending machine and bought a bag of chips.","data": {"testphase":"encoding","Condition":"Control","ConditionNum":4.0,"CB":1.0,"StoryNum":3.0}},
{"LineNum":18.0,"word":"Angie remembered that her pants were dry clean only and took them out of the machine.","data": {"testphase":"encoding","Condition":"Pre-boundary","ConditionNum":1.0,"CB":1.0,"StoryNum":3.0}},
{"LineNum":19.0,"word":"A while later, she chatted with the person using the washer next to hers.","data": {"testphase":"encoding","Condition":"Boundary","ConditionNum":2.0,"CB":1.0,"StoryNum":3.0}},
{"LineNum":20.0,"word":"Angie remembered that the washers were slow at this laundromat.","data": {"testphase":"encoding","Condition":"Pre-control","ConditionNum":3.0,"CB":1.0,"StoryNum":3.0}},
{"LineNum":21.0,"word":"A moment later, she looked around and saw that all of the dryers were taken.","data": {"testphase":"encoding","Condition":"Control","ConditionNum":4.0,"CB":1.0,"StoryNum":3.0}},
{"LineNum":22.0,"word":"She took Gone With the Wind out of her backpack.","data": {"testphase":"encoding","Condition":"Pre-boundary","ConditionNum":1.0,"CB":1.0,"StoryNum":3.0}},
{"LineNum":23.0,"word":"A while later, Angie lost her concentration because there was a lot going on around her.","data": {"testphase":"encoding","Condition":"Boundary","ConditionNum":2.0,"CB":1.0,"StoryNum":3.0}},
{"LineNum":24.0,"word":"She checked the dryers again and found they were still in use.","data": {"testphase":"encoding","Condition":"Pre-boundary","ConditionNum":1.0,"CB":1.0,"StoryNum":3.0}},
{"LineNum":25.0,"word":"A while later, she looked up at the television and watched some of the local news.","data": {"testphase":"encoding","Condition":"Boundary","ConditionNum":2.0,"CB":1.0,"StoryNum":3.0}},
{"LineNum":26.0,"word":"Angie heard a man playing a cd over the sound of the washing machines.","data": {"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":3.0}},
{"LineNum":27.0,"word":"Angie thought about asking the man to turn down his music.","data": {"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":3.0}},
{"LineNum":28.0,"word":"She went over to a dryer that had just been emptied.","data": {"testphase":"encoding","Condition":"Pre-control","ConditionNum":3.0,"CB":1.0,"StoryNum":3.0}},
{"LineNum":29.0,"word":"A moment later, Angie realized she was running low on fabric softener sheets.","data": {"testphase":"encoding","Condition":"Control","ConditionNum":4.0,"CB":1.0,"StoryNum":3.0}},
{"LineNum":30.0,"word":"She made a mental note to pick up some more on the way home.","data": {"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":3.0}},
{"LineNum":31.0,"word":"Angie thought it might take a while to dry all of her clothes in one load.","data": {"testphase":"encoding","Condition":"Pre-boundary","ConditionNum":1.0,"CB":1.0,"StoryNum":3.0}},
{"LineNum":32.0,"word":"A while later, she wondered whether or not she would need to get more quarters.","data": {"testphase":"encoding","Condition":"Boundary","ConditionNum":2.0,"CB":1.0,"StoryNum":3.0}},
{"LineNum":33.0,"word":"She put her laundry basket next to her dryer while waiting for her clothes to finish.","data": {"testphase":"encoding","Condition":"Pre-boundary","ConditionNum":1.0,"CB":1.0,"StoryNum":3.0}},
{"LineNum":34.0,"word":"A while later, she thought about other laundromats where the dryers were cheaper or free.","data": {"testphase":"encoding","Condition":"Boundary","ConditionNum":2.0,"CB":1.0,"StoryNum":3.0}},
{"LineNum":35.0,"word":"She decided to go to one with free dryers next time.","data": {"testphase":"encoding","Condition":"Pre-control","ConditionNum":3.0,"CB":1.0,"StoryNum":3.0}},
{"LineNum":36.0,"word":"A moment later, she noticed that the laundromat was quieter and starting to empty.","data": {"testphase":"encoding","Condition":"Control","ConditionNum":4.0,"CB":1.0,"StoryNum":3.0}},
{"LineNum":37.0,"word":"She folded her clean clothes and put them in the empty container.","data": {"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":3.0}},
{"LineNum":38.0,"word":"She packed up her things and left the laundromat, happy to have clean clothes.","data": {"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":3.0}}];
