var eStory4 = 
[{"LineNum":1.0,"word":"Phillip was planning a vacation for his family of four. ","data":{"testphase":"encoding","Condition":"Pre-control","ConditionNum":3.0,"CB":1.0,"StoryNum":4.0}},
{"LineNum":2.0,"word":"A moment later, he took out his calendar and looked for the best date. ","data":{"testphase":"encoding","Condition":"Control","ConditionNum":4.0,"CB":1.0,"StoryNum":4.0}},
{"LineNum":3.0,"word":"He decided they should go away for Christmas because everyone would have time off. ","data":{"testphase":"encoding","Condition":"Pre-boundary","ConditionNum":1.0,"CB":1.0,"StoryNum":4.0}},
{"LineNum":4.0,"word":"A while later, he limited his search to warm places since it would be a winter vacation. ","data":{"testphase":"encoding","Condition":"Boundary","ConditionNum":2.0,"CB":1.0,"StoryNum":4.0}},
{"LineNum":5.0,"word":"Phillip remembered that beach vacations were always his childhood favorites. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":4.0}},
{"LineNum":6.0,"word":"He investigated some suggestions that his family gave to him.","data":{"testphase":"encoding","Condition":"Pre-control","ConditionNum":3.0,"CB":1.0,"StoryNum":4.0}},
{"LineNum":7.0,"word":"A moment later, he browsed travel websites for inspiration and began to make a list. ","data":{"testphase":"encoding","Condition":"Control","ConditionNum":4.0,"CB":1.0,"StoryNum":4.0}},
{"LineNum":8.0,"word":"Phillip was happy that fares were cheaper if he booked well in advance. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":4.0}},
{"LineNum":9.0,"word":"He recalled his kids mentioning that they wanted to go to Disney World. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":4.0}},
{"LineNum":10.0,"word":"Phillip looked around online but knew he did not want a theme park. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":4.0}},
{"LineNum":11.0,"word":"He thought about the last vacation that his family had taken to the Grand Canyon. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":4.0}},
{"LineNum":12.0,"word":"He remembered how the long hours in the car led to a lot of fighting. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":4.0}},
{"LineNum":13.0,"word":"Phillip saw his kids playing in the yard with the dog. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":4.0}},
{"LineNum":14.0,"word":"He decided he would rather spend the vacation quietly relaxing. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":4.0}},
{"LineNum":15.0,"word":"Phillip wondered if there were seasonal travel deals that he could take advantage of.","data":{"testphase":"encoding","Condition":"Pre-boundary","ConditionNum":1.0,"CB":1.0,"StoryNum":4.0}},
{"LineNum":16.0,"word":"A while later, he realized that was unlikely because winter is a popular time for tropical climates. ","data":{"testphase":"encoding","Condition":"Boundary","ConditionNum":2.0,"CB":1.0,"StoryNum":4.0}},
{"LineNum":17.0,"word":"He accepted the idea that this was going to be an expensive trip.","data":{"testphase":"encoding","Condition":"Pre-control","ConditionNum":3.0,"CB":1.0,"StoryNum":4.0}},
{"LineNum":18.0,"word":"A moment later, Phillip discovered his kids were too old to get most of the child discounts. ","data":{"testphase":"encoding","Condition":"Control","ConditionNum":4.0,"CB":1.0,"StoryNum":4.0}},
{"LineNum":19.0,"word":"He thought about calling his travel agent to ask for suggestions.","data":{"testphase":"encoding","Condition":"Pre-boundary","ConditionNum":1.0,"CB":1.0,"StoryNum":4.0}},
{"LineNum":20.0,"word":"A while later, Phillip knew that he would have to find a compromise. ","data":{"testphase":"encoding","Condition":"Boundary","ConditionNum":2.0,"CB":1.0,"StoryNum":4.0}},
{"LineNum":21.0,"word":"He took out his travel guide and looked for options to show his family.","data":{"testphase":"encoding","Condition":"Pre-control","ConditionNum":3.0,"CB":1.0,"StoryNum":4.0}},
{"LineNum":22.0,"word":"A moment later, Phillip heard his wife downstairs preparing vegetable stew for dinner. ","data":{"testphase":"encoding","Condition":"Control","ConditionNum":4.0,"CB":1.0,"StoryNum":4.0}},
{"LineNum":23.0,"word":"The aromas of the meal made their way into his office. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":4.0}},
{"LineNum":24.0,"word":"Phillip began to get hungry and tried to focus on vacation planning.  ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":4.0}},
{"LineNum":25.0,"word":"He heard a travel commercial on the radio advertising camping trips.","data":{"testphase":"encoding","Condition":"Pre-control","ConditionNum":3.0,"CB":1.0,"StoryNum":4.0}},
{"LineNum":26.0,"word":"A moment later, Phillip went back and forth trying to decide which vacation to choose. ","data":{"testphase":"encoding","Condition":"Control","ConditionNum":4.0,"CB":1.0,"StoryNum":4.0}},
{"LineNum":27.0,"word":"He decided that a cruise ship would be a perfect compromise.","data":{"testphase":"encoding","Condition":"Pre-boundary","ConditionNum":1.0,"CB":1.0,"StoryNum":4.0}},
{"LineNum":28.0,"word":"A while later, he worried about upsetting his parents since his family would be gone for the holidays. ","data":{"testphase":"encoding","Condition":"Boundary","ConditionNum":2.0,"CB":1.0,"StoryNum":4.0}},
{"LineNum":29.0,"word":"He decided not to invite them along because they did not like to travel. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":4.0}},
{"LineNum":30.0,"word":"Phillip was happy that he had a vacation plan picked out.","data":{"testphase":"encoding","Condition":"Pre-boundary","ConditionNum":1.0,"CB":1.0,"StoryNum":4.0}},
{"LineNum":31.0,"word":"A while later, he took out a photo album from their last vacation and started browsing through it. ","data":{"testphase":"encoding","Condition":"Boundary","ConditionNum":2.0,"CB":1.0,"StoryNum":4.0}},
{"LineNum":32.0,"word":"He figured the kids could go to Disney World if the ship left from Florida.","data":{"testphase":"encoding","Condition":"Pre-control","ConditionNum":3.0,"CB":1.0,"StoryNum":4.0}},
{"LineNum":33.0,"word":"A moment later, he decided to put down a deposit as soon as possible. ","data":{"testphase":"encoding","Condition":"Control","ConditionNum":4.0,"CB":1.0,"StoryNum":4.0}},
{"LineNum":34.0,"word":"Phillip was happy that they would be spending time with each other.","data":{"testphase":"encoding","Condition":"Pre-boundary","ConditionNum":1.0,"CB":1.0,"StoryNum":4.0}},
{"LineNum":35.0,"word":"A while later, he knew his family would enjoy the trip since there was something for everyone. ","data":{"testphase":"encoding","Condition":"Boundary","ConditionNum":2.0,"CB":1.0,"StoryNum":4.0}},
{"LineNum":36.0,"word":"He figured his kids would enjoy the excitement of a cruise. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":4.0}},
{"LineNum":37.0,"word":"Phillip heard his dog barking in the yard and his wife calling him. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":4.0}},
{"LineNum":38.0,"word":"He went downstairs and told his kids to get ready for dinner. ","data":{"testphase":"encoding","Condition":null,"ConditionNum":null,"CB":1.0,"StoryNum":4.0}}]
