
var tStory1 = 
[{"QuestionNum":1,"word":"Sam shuffled through some papers and began to organize his notes from class.","data":{"testphase":"memTest","LineNum":5,"Condition":"Pre-control","ConditionNum":3,"CB":1,"StoryNum":1,"CorrAnswerLineNum":6,"CorrAnswer":"A moment later, Sam felt relieved to have organized notes to start from."}},
{"QuestionNum":2,"word":"He thought about the plot and started brainstorming thesis ideas for the report.","data":{"testphase":"memTest","LineNum":7,"Condition":"Pre-boundary","ConditionNum":1,"CB":1,"StoryNum":1,"CorrAnswerLineNum":8,"CorrAnswer":"A while later, Sam thought about two other classes for which he had read the play. "}},
{"QuestionNum":3,"word":"He thought about her college graduation ceremony last month.","data":{"testphase":"memTest","LineNum":12,"Condition":"Boundary","ConditionNum":2,"CB":1,"StoryNum":1,"CorrAnswerLineNum":13,"CorrAnswer":"Sam jotted down some notes about how to write his introduction."}},
{"QuestionNum":4,"word":"With a good outline it was time to start typing the report.","data":{"testphase":"memTest","LineNum":14,"Condition":"Control","ConditionNum":4,"CB":1,"StoryNum":1,"CorrAnswerLineNum":15,"CorrAnswer":"He turned on his computer and switched on his monitor."}},
{"QuestionNum":5,"word":"He thought about ordering a pizza from his favorite Italian place.","data":{"testphase":"memTest","LineNum":17,"Condition":"Pre-boundary","ConditionNum":1,"CB":1,"StoryNum":1,"CorrAnswerLineNum":18,"CorrAnswer":"A while later, he briefly looked around his room for snacks but tried not to get distracted."}},
{"QuestionNum":6,"word":"He looked over his outline again and realized he needed some additional information.","data":{"testphase":"memTest","LineNum":20,"Condition":"Pre-control","ConditionNum":3,"CB":1,"StoryNum":1,"CorrAnswerLineNum":21,"CorrAnswer":"A moment later, he took out a volume of Shakespeare's Collected Works for reference."}},
{"QuestionNum":7,"word":"He started to feel his eyes getting tired from looking at the monitor.","data":{"testphase":"memTest","LineNum":22,"Condition":"Pre-control","ConditionNum":3,"CB":1,"StoryNum":1,"CorrAnswerLineNum":23,"CorrAnswer":"A moment later, Sam put on his glasses so he could see the screen clearly."}},
{"QuestionNum":8,"word":"He turned on some music to help him focus on his work.","data":{"testphase":"memTest","LineNum":25,"Condition":"Pre-boundary","ConditionNum":1,"CB":1,"StoryNum":1,"CorrAnswerLineNum":26,"CorrAnswer":"A while later, he discovered some very useful information and made a few notes."}},
{"QuestionNum":9,"word":"He tried to come up with interesting ways to draw the reader into the paper.","data":{"testphase":"memTest","LineNum":30,"Condition":"Control","ConditionNum":4,"CB":1,"StoryNum":1,"CorrAnswerLineNum":31,"CorrAnswer":"He settled on a theme and started to type out his introduction."}},
{"QuestionNum":10,"word":"Sam started to realize that he enjoyed the teacher's challenging assignments.","data":{"testphase":"memTest","LineNum":32,"Condition":"Boundary","ConditionNum":2,"CB":1,"StoryNum":1,"CorrAnswerLineNum":33,"CorrAnswer":"Sam typed up a few supporting lines and started working on his final paragraph."}},
{"QuestionNum":11,"word":"He looked at a bag of chips that was sitting on his desk.","data":{"testphase":"memTest","LineNum":34,"Condition":"Control","ConditionNum":4,"CB":1,"StoryNum":1,"CorrAnswerLineNum":35,"CorrAnswer":"He tasted one and found out they were too stale to eat."}},
{"QuestionNum":12,"word":"Sam finished typing up the last paragraph of his report.","data":{"testphase":"memTest","LineNum":37,"Condition":"Boundary","ConditionNum":2,"CB":1,"StoryNum":1,"CorrAnswerLineNum":38,"CorrAnswer":"He took a last look over it, printed it out, and went to bed."}}]
