var tStory2 = 
[{"QuestionNum":1,"word":"She noticed that she had left her stereo on all day.","data":{"testphase":"memTest","LineNum":3,"Condition":"Pre-control","ConditionNum":3,"CB":1,"StoryNum":2,"CorrAnswerLineNum":4,"CorrAnswer":"A moment later, Nancy's stomach started to growl loudly since she had not eaten lunch. "}},
{"QuestionNum":2,"word":"She tried to decide what kind of meal to prepare. ","data":{"testphase":"memTest","LineNum":7,"Condition":"Boundary","ConditionNum":2,"CB":1,"StoryNum":2,"CorrAnswerLineNum":8,"CorrAnswer":"She took out some things from the pantry and refrigerator."}},
{"QuestionNum":3,"word":"She turned on her stove to heat up a pot of water. ","data":{"testphase":"memTest","LineNum":9,"Condition":"Control","ConditionNum":4,"CB":1,"StoryNum":2,"CorrAnswerLineNum":10,"CorrAnswer":"Nancy noticed that her apartment was warm that evening. "}},
{"QuestionNum":4,"word":"She realized she had forgotten to leave a window open when she left for work.","data":{"testphase":"memTest","LineNum":11,"Condition":"Pre-control","ConditionNum":3,"CB":1,"StoryNum":2,"CorrAnswerLineNum":12,"CorrAnswer":"A moment later, she decided to turn on the air conditioner for a little while. "}},
{"QuestionNum":5,"word":"Nancy put some pasta in the pot and added some salt to the water. ","data":{"testphase":"memTest","LineNum":15,"Condition":"Boundary","ConditionNum":2,"CB":1,"StoryNum":2,"CorrAnswerLineNum":16,"CorrAnswer":"She set the kitchen table with a placemat, a glass and silverware. "}},
{"QuestionNum":6,"word":"She checked her dinner and prepared a plate when it was ready. ","data":{"testphase":"memTest","LineNum":20,"Condition":"Control","ConditionNum":4,"CB":1,"StoryNum":2,"CorrAnswerLineNum":21,"CorrAnswer":"She grabbed a napkin to wipe up some sauce that had spilled. "}},
{"QuestionNum":7,"word":"She finished eating and called one of her friends about seeing a movie.","data":{"testphase":"memTest","LineNum":24,"Condition":"Pre-boundary","ConditionNum":1,"CB":1,"StoryNum":2,"CorrAnswerLineNum":25,"CorrAnswer":"A while later, she decided to clean up her dirty dishes before doing anything else. "}},
{"QuestionNum":8,"word":"She filled the sink with water to first soak the dishes.","data":{"testphase":"memTest","LineNum":26,"Condition":"Pre-control","ConditionNum":3,"CB":1,"StoryNum":2,"CorrAnswerLineNum":27,"CorrAnswer":"A moment later, she added some dish soap to the water and watched the sink fill with bubbles. "}},
{"QuestionNum":9,"word":"Nancy put the soap on a sponge and got started.","data":{"testphase":"memTest","LineNum":28,"Condition":"Pre-boundary","ConditionNum":1,"CB":1,"StoryNum":2,"CorrAnswerLineNum":29,"CorrAnswer":"A while later, she turned on the radio to listen to some music. "}},
{"QuestionNum":10,"word":"She left the dishes in the rack on the counter to dry. ","data":{"testphase":"memTest","LineNum":32,"Condition":"Control","ConditionNum":4,"CB":1,"StoryNum":2,"CorrAnswerLineNum":33,"CorrAnswer":"She decided to read for a little bit before going to bed."}},
{"QuestionNum":11,"word":"She remembered that she drank a cup of coffee before leaving work. ","data":{"testphase":"memTest","LineNum":34,"Condition":"Boundary","ConditionNum":2,"CB":1,"StoryNum":2,"CorrAnswerLineNum":35,"CorrAnswer":"She took out a book that she thought would make her feel tired. "}},
{"QuestionNum":12,"word":"Nancy read her book and hoped she would be able to sleep.","data":{"testphase":"memTest","LineNum":36,"Condition":"Pre-boundary","ConditionNum":1,"CB":1,"StoryNum":2,"CorrAnswerLineNum":37,"CorrAnswer":"A while later, her cat came into the room and brushed her foot with his tail. "}}]
