var tStory3 = 
[{"QuestionNum":1,"word":"An employee came up to her and apologized because they were very busy.","data":{"testphase":"memTest","LineNum":4,"Condition":"Pre-control","ConditionNum":3,"CB":1,"StoryNum":3,"CorrAnswerLineNum":5,"CorrAnswer":"A moment later, some washers started to open up while she waited."}},
{"QuestionNum":2,"word":"She put four coins into the washing machine to get it started.","data":{"testphase":"memTest","LineNum":8,"Condition":"Control","ConditionNum":4,"CB":1,"StoryNum":3,"CorrAnswerLineNum":9,"CorrAnswer":"Angie measured out a cup of detergent and added it to the water."}},
{"QuestionNum":3,"word":"She smiled at a child who was playing with a ball nearby.","data":{"testphase":"memTest","LineNum":13,"Condition":"Boundary","ConditionNum":2,"CB":1,"StoryNum":3,"CorrAnswerLineNum":14,"CorrAnswer":"She started another washing machine for her light colored clothes."}},
{"QuestionNum":4,"word":"She added a pair of slacks she had forgotten as the machine ran.","data":{"testphase":"memTest","LineNum":16,"Condition":"Pre-control","ConditionNum":3,"CB":1,"StoryNum":3,"CorrAnswerLineNum":17,"CorrAnswer":"A moment later, she walked over to a vending machine and bought a bag of chips."}},
{"QuestionNum":5,"word":"Angie remembered that her pants were dry clean only and took them out of the machine.","data":{"testphase":"memTest","LineNum":18,"Condition":"Pre-boundary","ConditionNum":1,"CB":1,"StoryNum":3,"CorrAnswerLineNum":19,"CorrAnswer":"A while later, she chatted with the person using the washer next to hers."}},
{"QuestionNum":6,"word":"She looked around and saw that all of the dryers were taken.","data":{"testphase":"memTest","LineNum":21,"Condition":"Control","ConditionNum":4,"CB":1,"StoryNum":3,"CorrAnswerLineNum":22,"CorrAnswer":"She took Gone With the Wind out of her backpack."}},
{"QuestionNum":7,"word":"Angie lost her concentration because there was a lot going on around her.","data":{"testphase":"memTest","LineNum":23,"Condition":"Boundary","ConditionNum":2,"CB":1,"StoryNum":3,"CorrAnswerLineNum":24,"CorrAnswer":"She checked the dryers again and found they were still in use."}},
{"QuestionNum":8,"word":"She looked up at the television and watched some of the local news.","data":{"testphase":"memTest","LineNum":25,"Condition":"Boundary","ConditionNum":2,"CB":1,"StoryNum":3,"CorrAnswerLineNum":26,"CorrAnswer":"Angie heard a man playing a cd over the sound of the washing machines."}},
{"QuestionNum":9,"word":"She went over to a dryer that had just been emptied.","data":{"testphase":"memTest","LineNum":28,"Condition":"Pre-control","ConditionNum":3,"CB":1,"StoryNum":3,"CorrAnswerLineNum":29,"CorrAnswer":"A moment later, Angie realized she was running low on fabric softener sheets."}},
{"QuestionNum":10,"word":"Angie thought it might take a while to dry all of her clothes in one load.","data":{"testphase":"memTest","LineNum":31,"Condition":"Pre-boundary","ConditionNum":1,"CB":1,"StoryNum":3,"CorrAnswerLineNum":32,"CorrAnswer":"A while later, she wondered whether or not she would need to get more quarters."}},
{"QuestionNum":11,"word":"She put her laundry basket next to her dryer while waiting for her clothes to finish.","data":{"testphase":"memTest","LineNum":33,"Condition":"Pre-boundary","ConditionNum":1,"CB":1,"StoryNum":3,"CorrAnswerLineNum":34,"CorrAnswer":"A while later, she thought about other laundromats where the dryers were cheaper or free."}},
{"QuestionNum":12,"word":"She noticed that the laundromat was quieter and starting to empty.","data":{"testphase":"memTest","LineNum":36,"Condition":"Control","ConditionNum":4,"CB":1,"StoryNum":3,"CorrAnswerLineNum":37,"CorrAnswer":"She folded her clean clothes and put them in the empty container."}}]
