var tStory4 =
[{"QuestionNum":1,"word":"He took out his calendar and looked for the best date. ","data":{"testphase":"memTest","LineNum":2,"Condition":"Control","ConditionNum":4,"CB":1,"StoryNum":4,"CorrAnswerLineNum":3,"CorrAnswer":"He decided they should go away for Christmas because everyone would have time off."}},
{"QuestionNum":2,"word":"He limited his search to warm places since it would be a winter vacation. ","data":{"testphase":"memTest","LineNum":4,"Condition":"Boundary","ConditionNum":2,"CB":1,"StoryNum":4,"CorrAnswerLineNum":5,"CorrAnswer":"Phillip remembered that beach vacations were always his childhood favorites. "}},
{"QuestionNum":3,"word":"He investigated some suggestions that his family gave to him.","data":{"testphase":"memTest","LineNum":6,"Condition":"Pre-control","ConditionNum":3,"CB":1,"StoryNum":4,"CorrAnswerLineNum":7,"CorrAnswer":"A moment later, he browsed travel websites for inspiration and began to make a list. "}},
{"QuestionNum":4,"word":"Phillip wondered if there were seasonal travel deals that he could take advantage of.","data":{"testphase":"memTest","LineNum":15,"Condition":"Pre-boundary","ConditionNum":1,"CB":1,"StoryNum":4,"CorrAnswerLineNum":16,"CorrAnswer":"A while later, he realized that was unlikely because winter is a popular time for tropical climates. "}},
{"QuestionNum":5,"word":"He accepted the idea that this was going to be an expensive trip.","data":{"testphase":"memTest","LineNum":17,"Condition":"Pre-control","ConditionNum":3,"CB":1,"StoryNum":4,"CorrAnswerLineNum":18,"CorrAnswer":"A moment later, Phillip discovered his kids were too old to get most of the child discounts. "}},
{"QuestionNum":6,"word":"He thought about calling his travel agent to ask for suggestions.","data":{"testphase":"memTest","LineNum":19,"Condition":"Pre-boundary","ConditionNum":1,"CB":1,"StoryNum":4,"CorrAnswerLineNum":20,"CorrAnswer":"A while later, Phillip knew that he would have to find a compromise. "}},
{"QuestionNum":7,"word":"He took out his travel guide and looked for options to show his family.","data":{"testphase":"memTest","LineNum":21,"Condition":"Pre-control","ConditionNum":3,"CB":1,"StoryNum":4,"CorrAnswerLineNum":22,"CorrAnswer":"A moment later, Phillip heard his wife downstairs preparing vegetable stew for dinner. "}},
{"QuestionNum":8,"word":"Phillip went back and forth trying to decide which vacation to choose. ","data":{"testphase":"memTest","LineNum":26,"Condition":"Control","ConditionNum":4,"CB":1,"StoryNum":4,"CorrAnswerLineNum":27,"CorrAnswer":"He decided that a cruise ship would be a perfect compromise."}},
{"QuestionNum":9,"word":"He worried about upsetting his parents since his family would be gone for the holidays. ","data":{"testphase":"memTest","LineNum":28,"Condition":"Boundary","ConditionNum":2,"CB":1,"StoryNum":4,"CorrAnswerLineNum":29,"CorrAnswer":"He decided not to invite them along because they did not like to travel. "}},
{"QuestionNum":10,"word":"Phillip was happy that he had a vacation plan picked out.","data":{"testphase":"memTest","LineNum":30,"Condition":"Pre-boundary","ConditionNum":1,"CB":1,"StoryNum":4,"CorrAnswerLineNum":31,"CorrAnswer":"A while later, he took out a photo album from their last vacation and started browsing through it. "}},
{"QuestionNum":11,"word":"He decided to put down a deposit as soon as possible. ","data":{"testphase":"memTest","LineNum":33,"Condition":"Control","ConditionNum":4,"CB":1,"StoryNum":4,"CorrAnswerLineNum":34,"CorrAnswer":"Phillip was happy that they would be spending time with each other."}},
{"QuestionNum":12,"word":"He knew his family would enjoy the trip since there was something for everyone. ","data":{"testphase":"memTest","LineNum":35,"Condition":"Boundary","ConditionNum":2,"CB":1,"StoryNum":4,"CorrAnswerLineNum":36,"CorrAnswer":"He figured his kids would enjoy the excitement of a cruise. "}}]
